# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock_market.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stock_market.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12stock_market.proto\x12\x0cstock_market\"\x1e\n\x0cStockRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"A\n\rStockResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32V\n\nStockPrice\x12H\n\rGetStockPrice\x12\x1a.stock_market.StockRequest\x1a\x1b.stock_market.StockResponseB!\n\x1d\x62r.com.rafaellino.stockmarketP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_market_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035br.com.rafaellino.stockmarketP\001'
  _globals['_STOCKREQUEST']._serialized_start=36
  _globals['_STOCKREQUEST']._serialized_end=66
  _globals['_STOCKRESPONSE']._serialized_start=68
  _globals['_STOCKRESPONSE']._serialized_end=133
  _globals['_STOCKPRICE']._serialized_start=135
  _globals['_STOCKPRICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
